describe('Unity visual regression tests', function() {
  it('Test the Unity styles.', function(browser) {
    browser
      .navigateTo('pages/style-guide.html')
      .pause(2000)
      .assert.screenshotIdenticalToBaseline('h1',  /* Optional */ 'h1-small')
      .assert.screenshotIdenticalToBaseline('h2',  /* Optional */ 'h2-small')
      .assert.screenshotIdenticalToBaseline('h3',  /* Optional */ 'h3-small')
      .assert.screenshotIdenticalToBaseline('h4',  /* Optional */ 'h4-small')
      .assert.screenshotIdenticalToBaseline('h5',  /* Optional */ 'h5-small')
      .assert.screenshotIdenticalToBaseline('h6',  /* Optional */ 'h6-small')
      .assert.screenshotIdenticalToBaseline('ol',  /* Optional */ 'ol-small')
      .assert.screenshotIdenticalToBaseline('article ul',  /* Optional */ 'ul-small')
      .assert.screenshotIdenticalToBaseline('code',  /* Optional */ 'code-small')
      .assert.screenshotIdenticalToBaseline('pre',  /* Optional */ 'pre-small')
      .assert.screenshotIdenticalToBaseline('table',  /* Optional */ 'table-small')
      .assert.screenshotIdenticalToBaseline('blockquote',  /* Optional */ 'blockquote-small')
      .windowSize('current', 640, 1500)
      .pause(2000)
      .assert.screenshotIdenticalToBaseline('h1',  /* Optional */ 'h1-medium')
      .assert.screenshotIdenticalToBaseline('h2',  /* Optional */ 'h2-medium')
      .assert.screenshotIdenticalToBaseline('h3',  /* Optional */ 'h3-medium')
      .assert.screenshotIdenticalToBaseline('h4',  /* Optional */ 'h4-medium')
      .assert.screenshotIdenticalToBaseline('h5',  /* Optional */ 'h5-medium')
      .assert.screenshotIdenticalToBaseline('h6',  /* Optional */ 'h6-medium')
      .assert.screenshotIdenticalToBaseline('ol',  /* Optional */ 'ol-medium')
      .assert.screenshotIdenticalToBaseline('article ul',  /* Optional */ 'ul-medium')
      .assert.screenshotIdenticalToBaseline('code',  /* Optional */ 'code-medium')
      .assert.screenshotIdenticalToBaseline('pre',  /* Optional */ 'pre-medium')
      .assert.screenshotIdenticalToBaseline('table',  /* Optional */ 'table-medium')
      .assert.screenshotIdenticalToBaseline('blockquote',  /* Optional */ 'blockquote-medium')      .windowSize('current', 900, 1500)
      .pause(2000)
      .assert.screenshotIdenticalToBaseline('h1',  /* Optional */ 'h1-mlarge')
      .assert.screenshotIdenticalToBaseline('h2',  /* Optional */ 'h2-mlarge')
      .assert.screenshotIdenticalToBaseline('h3',  /* Optional */ 'h3-mlarge')
      .assert.screenshotIdenticalToBaseline('h4',  /* Optional */ 'h4-mlarge')
      .assert.screenshotIdenticalToBaseline('h5',  /* Optional */ 'h5-mlarge')
      .assert.screenshotIdenticalToBaseline('h6',  /* Optional */ 'h6-mlarge')
      .assert.screenshotIdenticalToBaseline('ol',  /* Optional */ 'ol-mlarge')
      .assert.screenshotIdenticalToBaseline('article ul',  /* Optional */ 'ul-mlarge')
      .assert.screenshotIdenticalToBaseline('code',  /* Optional */ 'code-mlarge')
      .assert.screenshotIdenticalToBaseline('pre',  /* Optional */ 'pre-mlarge')
      .assert.screenshotIdenticalToBaseline('table',  /* Optional */ 'table-mlarge')
      .assert.screenshotIdenticalToBaseline('blockquote',  /* Optional */ 'blockquote-mlarge')      .windowSize('current', 1024, 1500)
      .pause(2000)
      .assert.screenshotIdenticalToBaseline('h1',  /* Optional */ 'h1-large')
      .assert.screenshotIdenticalToBaseline('h2',  /* Optional */ 'h2-large')
      .assert.screenshotIdenticalToBaseline('h3',  /* Optional */ 'h3-large')
      .assert.screenshotIdenticalToBaseline('h4',  /* Optional */ 'h4-large')
      .assert.screenshotIdenticalToBaseline('h5',  /* Optional */ 'h5-large')
      .assert.screenshotIdenticalToBaseline('h6',  /* Optional */ 'h6-large')
      .assert.screenshotIdenticalToBaseline('ol',  /* Optional */ 'ol-large')
      .assert.screenshotIdenticalToBaseline('article ul',  /* Optional */ 'ul-large')
      .assert.screenshotIdenticalToBaseline('code',  /* Optional */ 'code-large')
      .assert.screenshotIdenticalToBaseline('pre',  /* Optional */ 'pre-large')
      .assert.screenshotIdenticalToBaseline('table',  /* Optional */ 'table-large')
      .assert.screenshotIdenticalToBaseline('blockquote',  /* Optional */ 'blockquote-large')         .windowSize('current', 1260, 1500)
      .pause(2000)
      .assert.screenshotIdenticalToBaseline('h1',  /* Optional */ 'h1-xlarge')
      .assert.screenshotIdenticalToBaseline('h2',  /* Optional */ 'h2-xlarge')
      .assert.screenshotIdenticalToBaseline('h3',  /* Optional */ 'h3-xlarge')
      .assert.screenshotIdenticalToBaseline('h4',  /* Optional */ 'h4-xlarge')
      .assert.screenshotIdenticalToBaseline('h5',  /* Optional */ 'h5-xlarge')
      .assert.screenshotIdenticalToBaseline('h6',  /* Optional */ 'h6-xlarge')
      .assert.screenshotIdenticalToBaseline('ol',  /* Optional */ 'ol-xlarge')
      .assert.screenshotIdenticalToBaseline('article ul',  /* Optional */ 'ul-xlarge')
      .assert.screenshotIdenticalToBaseline('code',  /* Optional */ 'code-xlarge')
      .assert.screenshotIdenticalToBaseline('pre',  /* Optional */ 'pre-xlarge')
      .assert.screenshotIdenticalToBaseline('table',  /* Optional */ 'table-xlarge')
      .assert.screenshotIdenticalToBaseline('blockquote',  /* Optional */ 'blockquote-xlarge')
      .windowSize('current', 1440, 1500)
      .pause(2000)
      .assert.screenshotIdenticalToBaseline('h1',  /* Optional */ 'h1-xxlarge')
      .assert.screenshotIdenticalToBaseline('h2',  /* Optional */ 'h2-xxlarge')
      .assert.screenshotIdenticalToBaseline('h3',  /* Optional */ 'h3-xxlarge')
      .assert.screenshotIdenticalToBaseline('h4',  /* Optional */ 'h4-xxlarge')
      .assert.screenshotIdenticalToBaseline('h5',  /* Optional */ 'h5-xxlarge')
      .assert.screenshotIdenticalToBaseline('h6',  /* Optional */ 'h6-xxlarge')
      .assert.screenshotIdenticalToBaseline('ol',  /* Optional */ 'ol-xxlarge')
      .assert.screenshotIdenticalToBaseline('article ul',  /* Optional */ 'ul-xxlarge')
      .assert.screenshotIdenticalToBaseline('code',  /* Optional */ 'code-xxlarge')
      .assert.screenshotIdenticalToBaseline('pre',  /* Optional */ 'pre-xxlarge')
      .assert.screenshotIdenticalToBaseline('table',  /* Optional */ 'table-xxlarge')
      .assert.screenshotIdenticalToBaseline('blockquote',  /* Optional */ 'blockquote-xxlarge')
  })
})
